stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - review
  - production

image: docker/compose:latest
services:
  - docker:dind 

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo /update-git-tag.sh
    # - docker build -t devops-app:v1 .
    - echo "Compile complete."
  #only:
  #  - merge_requests
  #  - master


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Maven test started"
    # - “mvn test”
    - echo "Code coverage is 90%"
  only:
    - merge_requests
    - master

review-job:
  stage: review  
  script:
    - echo "revising application..."
    - echo "Application successfully reviewed."
  only:
    - merge_requests

deploy-job:      # This job runs in the deploy stage.
  stage: production  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - master