stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - review
  - production

image: docker:20.10.16
services:
  - docker:20.10.16-dind

build-job:
  tags:       # This job runs in the build stage, which runs first.
  - builder
  stage: build
  before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - echo "Compiling the code..."
    - docker build -f docker-config/app/Dockerfile --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - echo "Compile complete."
  only:
    - merge_requests
    - master


unit-test-job:   # This job runs in the test stage.
  image: maven:3
  tags:
  - builder
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Maven test started"
    - mvn test
    - echo "######------COVERAGE-------#######"
    - cat target/site/jacoco/index.html | grep -o '<td class="ctr2" id="c0">.*</td>'

  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST.*.xml
        - target/surefire/TEST.*.xml
  only:
    - merge_requests
    - master

review-job:
  tags:
  - executor
  stage: review  
  script:
    - echo "revising application..."
    - echo "Application successfully reviewed."
  only:
    - merge_requests

deploy-job:      # This job runs in the deploy stage.
  tags:
  - executor
  stage: production  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - docker-compose up -d
    - echo "Application successfully deployed."
  only:
    - master