version: '3'

networks: 
  mysql-network:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: ./docker-config/app/Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    secrets:
       - db_password
    ports: 
      - "9000:8080"
    networks:
      - mysql-network
    depends_on:
      - "db"
  db:
    build: ./docker-config/db/
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-network
  
secrets:
  db_password:
    external: true
  db_root_password:
    external: true
