version: '3'

networks: 
  mysql-network:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

services:
  proxy:
    build: ./docker-config/proxy
    ports: 
      - "80:81"
      - "443:443"
    depends_on: 
      - app1
      - app2
      - app3
    networks:
      - mysql-network

  app1:
    build:
      context: ./
      dockerfile: ./docker-config/app/Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    secrets:
       - db_password
    networks:
      - mysql-network
    depends_on:
      - "db"

  app2:
    build:
      context: ./
      dockerfile: ./docker-config/app/Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    secrets:
       - db_password
    networks:
      - mysql-network
    depends_on:
      - "db"  

  app3:
    build:
      context: ./
      dockerfile: ./docker-config/app/Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
    secrets:
       - db_password
    networks:
      - mysql-network
    depends_on:
      - "db"  

  db:
    build: ./docker-config/db/
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-network
