version: "3"

services:
  reverse-proxy:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    networks:
      - traefik
    ports:
      #Acesso ao servico
      - "80:80"
      #Acesso ao dashboard
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  webnet:
  traefik:
    name: traefik
