- hosts: runner-server-1
  become: yes
  vars: 
    reg_token: "{{ lookup('file','registration.token.env') }}"
    
  tasks:
    - name: Instalando dependencias
      apt: 
        name: ['apt-transport-https','ca-certificates','curl','gnupg','lsb-release']
        state: present

    - name: Adicionando Docker GPG apt Key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
    
    - name: Adicionando Docker repositorio
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

    - name: Atualizando apt e instalando docker-ce
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io'] 
        state: latest 
        update_cache: yes

    - name: Baixando gitlab-runner
      shell: curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_$(dpkg --print-architecture).deb"

    - name: Instalando gitlab-runner
      shell: dpkg -i gitlab-runner_$(dpkg --print-architecture).deb
  
    - name: Liberando user do gitlab para uso do docker
      shell: usermod -aG docker gitlab-runner

    - name: Registrando gitlab-runner como docker executor
      shell: sudo gitlab-runner register -n \
          --url "https://gitlab.com/" \
          --registration-token {{ reg_token }} \
          --executor docker \
          --description "VM-Docker-Build" \
          --docker-image "docker:20.10.16" \
          --docker-privileged \
          --docker-volumes "/certs/client"
          --tag-list "devops, builder" \
          

- hosts: runner-server-2
  become: yes
  vars: 
    reg_token: "{{ lookup('file','registration.token.env') }}"
    
  tasks:
    - name: Instalando dependencias
      apt: 
        name: ['apt-transport-https','ca-certificates','curl','gnupg','lsb-release']
        state: present

    - name: Adicionando Docker GPG apt Key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
    
    - name: Adicionando Docker repositorio
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

    - name: Atualizando apt e instalando docker-ce
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io'] 
        state: latest 
        update_cache: yes

    - name: Adicionando o usuario "ansible_ubuntu_demo" dentro do grupo "docker"
      remote_user: ansible_ubuntu_demo
      user:
        name: "ansible_ubuntu_demo"
        group: "docker"
        append: yes
      tags:
        - docker
        
    - name: Instalando docker-compose do repositorio oficial do github 
      remote_user: ansible_ubuntu_demo
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Baixando gitlab-runner
      shell: curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_$(dpkg --print-architecture).deb"

    - name: Instalando gitlab-runner
      shell: dpkg -i gitlab-runner_$(dpkg --print-architecture).deb
  
    - name: Liberando user do gitlab para uso do docker
      shell: usermod -aG docker gitlab-runner

    - name: Registrando gitlab-runner como docker executor
      shell: sudo gitlab-runner register -n \
          --url "https://gitlab.com/" \
          --registration-token {{ reg_token }} \
          --executor docker \
          --description "VM-Docker-Executor" \
          --docker-image "docker:20.10.16" \
          --docker-privileged \
          --docker-volumes "/certs/client"
          --tag-list "devops, executor" \
    

